GET https://the-anything-blog1.herokuapp.com/games

###

GET http://localhost:5000/tech
###

GET https://the-anything-blog1.herokuapp.com/users/


###


POST https://the-anything-blog1.herokuapp.com/music/music
Authorization: bearer- eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZhODIzMTVlMzE2MmQxMmMwZjFmY2UiLCJpYXQiOjE2NTIxODQwMTR9.LdI9A3yAQIgpBREZm4C-OX2m4q7s_TwTdBjjEzidYwU
Content-Type: application/json

{
    "main_image": "https://i.postimg.cc/PqjKcDc4/download.webp",
    "title": "Vape tricks",
    "subtitle": "vape",
    "desc": "idk",
    "category": "lifestyle"
}


###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "username": "kohosfbj",
    "email": "kohonak856@pantabi.com",
    "password": "123456789"
}

###

POST http://localhost:5000/users/signin
Content-Type: application/json
authorization: authHeader

{
    "email": "jason@lifechoices.co.za",
    "password": "123456789"
}
###

DELETE http://localhost:5000/lifestyles/627bbecae19a11aa14f40eb5
Authorization: bearer- eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjZhODIzMTVlMzE2MmQxMmMwZjFmY2UiLCJpYXQiOjE2NTIxODQwMTR9.LdI9A3yAQIgpBREZm4C-OX2m4q7s_TwTdBjjEzidYwU
Content-Type: application/json

###

DELETE http://localhost:5000/users/626a4304ea036aefcbbb4c7c


###

POST http://localhost:5000/id/reaction
Content-Type: application/json

{
    "title": "kjhg",
    "subtitle": "uiyurt",
    "desc": "imyuntgrvf",
    "category": ",umyjntbg"
}